2025-05-02 12:38:44.674 | INFO     | datatrove.utils.logging:add_task_logger:58 - Launching pipeline for rank=0
2025-05-02 12:38:44.675 | INFO     | datatrove.utils.logging:log_pipeline:90 - 
--- 🛠️ PIPELINE 🛠
📖 - READER: 🐿 Jsonl
None: None
None: None
🔻 - FILTER: 🌍 Language ID
💽 - WRITER: 🐿 Jsonl
2025-05-02 12:38:44.676 | ERROR    | datatrove.executor.base:_run_for_rank:108 - No files found on /Users/adrienloizeau/dev/scratchGPT/data/raw!
Traceback (most recent call last):

  File "/Users/adrienloizeau/dev/scratchGPT/data_pipeline.py", line 77, in <module>
    executor.run()
    │        └ <function LocalPipelineExecutor.run at 0x11afba0e0>
    └ <datatrove.executor.local.LocalPipelineExecutor object at 0x11afc7880>

  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/executor/local.py", line 127, in run
    stats.append(self._launch_run_for_rank(rank, ranks_q))
    │     │      │    │                    │     └ <AutoProxy[Queue] object, typeid 'Queue' at 0x119eaa440>
    │     │      │    │                    └ 0
    │     │      │    └ <function LocalPipelineExecutor._launch_run_for_rank at 0x11afba050>
    │     │      └ <datatrove.executor.local.LocalPipelineExecutor object at 0x11afc7880>
    │     └ <method 'append' of 'list' objects>
    └ []
  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/executor/local.py", line 76, in _launch_run_for_rank
    return self._run_for_rank(rank, local_rank)
           │    │             │     └ 0
           │    │             └ 0
           │    └ <function PipelineExecutor._run_for_rank at 0x11afb9c60>
           └ <datatrove.executor.local.LocalPipelineExecutor object at 0x11afc7880>
> File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/executor/base.py", line 96, in _run_for_rank
    deque(pipelined_data, maxlen=0)
    │     └ <generator object DiskWriter.run at 0x11cecc820>
    └ <class 'collections.deque'>
  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/pipeline/writers/disk_base.py", line 178, in run
    for document in data:
                    └ <generator object BaseFilter.run at 0x11cecc430>
  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/pipeline/filters/base_filter.py", line 64, in run
    for batch in batched(data, self.batch_size):
                 │       │     │    └ 1
                 │       │     └ 🔻 - FILTER: 🌍 Language ID
                 │       └ <generator object ScoreFilter.run at 0x11cecc5f0>
                 └ <function batched at 0x11ac681f0>
  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/utils/batching.py", line 20, in batched
    while batch := list(itertools.islice(it, n)):
                        │         │      │   └ 1
                        │         │      └ <generator object ScoreFilter.run at 0x11cecc5f0>
                        │         └ <class 'itertools.islice'>
                        └ <module 'itertools' (built-in)>

  File "/Users/adrienloizeau/dev/scratchGPT/data_pipeline.py", line 42, in run
    for document in data:
        │           └ <generator object MergeFields.run at 0x11cecc660>
        └ {'title': 'How to establish first use in commerce?', 'body': "I recently learned that it's not the first person to register a...

  File "/Users/adrienloizeau/dev/scratchGPT/data_pipeline.py", line 33, in run
    for document in data:
        │           └ <generator object BaseDiskReader.run at 0x11cecc6d0>
        └ {'title': 'How to establish first use in commerce?', 'body': "I recently learned that it's not the first person to register a...

  File "/Users/adrienloizeau/opt/anaconda3/envs/lerobot/lib/python3.10/site-packages/datatrove/pipeline/readers/base.py", line 238, in run
    raise RuntimeError(f"No files found on {self.data_folder.path}!")

RuntimeError: No files found on /Users/adrienloizeau/dev/scratchGPT/data/raw!
